### ISSUE TITLE
Update example datasettemplates

### ISSUE THREAD

**Issue by antru6** [semagrow/kobe#36]
Update dataset server templates to work with and without delays (make use of the $USE_ISTIO flag).

**Comment by acharal** [comment]
Why do you need the switch on the dataset server template and not on the experiment?
My understanding is that network delays is a characteristic of an experiment.

**Comment by antru6** [comment]
As seen for example in https://github.com/semagrow/kobe/pull/22/commits/ea9121dbd0a2b25184057a81638a4b492c63374e the dataset server needs to wait for Sidecar
However, the new templates (cf. https://github.com/semagrow/kobe/pull/29) that use init containers do not have this part.
