### ISSUE TITLE
Installation details - ReadMe

### ISSUE THREAD

**Issue by AmrTAzzam** [semagrow/kobe#56]
It is not clear in the readme how to install the prerequisites. I could not use kobe because I did not manage to install the list of the mentioned prerequisites. Detailed explanation would be a great enhancement. 

Prerequisites
Kubernetes >= 1.8.0
kubectl configured for the Kubernetes cluster
Helm version 3 (for the Evaluation Metrics Extraction subsystem)
nfs-commons installed in the nodes of the cluster. If in Debian or Ubuntu you can install it using apt-get install nfs-common

**Comment by stasinos** [comment]
@AmrTAzzam please see updated README, currently still in devel branch.
